import { readFile, writeFile } from 'node:fs/promises';
import type { ScryfallCard } from '../src/types/scryfall.js';
import { parseDecklist, buildDeckMetrics, type ParsedDeck } from '../src/services/deck.js';
import { getCardsByIdentifiers, inferCardRoles, type CardIdentifierInput } from '../src/services/scryfall.js';
import { validateCommanderDeck } from '../src/services/commander-rules.js';
import { simulateDeckGameplayV06, type PodPressureV06 } from '../src/services/simulation-v06.js';

const A11='test-results/exploratory/scions-spellcraft-a11-control-deck.txt';
const EXT='test-results/exploratory/scions-spellcraft-external-comparison-deck.txt';
const STOCK='test-results/exploratory/scions-spellcraft-stock-deck.txt';
const norm=(v:string)=>v.trim().toLowerCase();
const rec=(v:unknown):Record<string,unknown>=>v&&typeof v==='object'&&!Array.isArray(v)?v as Record<string,unknown>:{};
const num=(v:unknown)=>typeof v==='number'&&Number.isFinite(v)?v:0;
const avg=(v:number[])=>v.length?v.reduce((a,b)=>a+b,0)/v.length:0;
interface Deck{parsed:ParsedDeck;cards:ScryfallCard[];notFound:string[];}
function ids(p:ParsedDeck):CardIdentifierInput[]{return [...p.commanders,...p.main].map(e=>({name:e.name}));}
async function resolve(text:string):Promise<Deck>{const parsed=parseDecklist(text);const r=await getCardsByIdentifiers(ids(parsed));return{parsed,cards:r.cards,notFound:r.notFound};}
function card(d:Deck,name:string){return d.cards.find(c=>norm(c.name)===norm(name)||norm(c.name.split(' // ')[0]??'')===norm(name));}
function mv(cost:string){let n=0;for(const m of cost.matchAll(/\{([^}]+)\}/g)){const x=(m[1]??'').toUpperCase();if(/^\d+$/.test(x))n+=Number(x);else if(/^[WUBRGC]$/.test(x)||x.includes('/'))n+=1;}return n;}
function qualifies(type:string|undefined,cost:string|undefined,fallback:number){const t=(type??'').toLowerCase();return !t.includes('creature')&&!t.includes('land')&&(cost?mv(cost):fallback)>=3;}
function yOffers(d:Deck){let total=0,instant=0;const names:string[]=[];for(const e of d.parsed.main){const c=card(d,e.name);if(!c)continue;const faces=c.card_faces??[];let q=false,qi=false;if(faces.length){const qs=faces.filter(f=>qualifies(f.type_line,f.mana_cost,c.cmc));q=qs.length>0;qi=qs.some(f=>(f.type_line??'').toLowerCase().includes('instant'));}else{q=qualifies(c.type_line,c.mana_cost,c.cmc);qi=q&&c.type_line.toLowerCase().includes('instant');}if(q){total+=e.quantity;names.push(e.name);if(qi)instant+=e.quantity;}}return{total,instant,names};}
function typeCounts(d:Deck){const o={land:0,creature:0,instant:0,sorcery:0,artifact:0,enchantment:0,other:0};for(const e of d.parsed.main){const c=card(d,e.name);if(!c)continue;const t=c.type_line.toLowerCase(),q=e.quantity;if(t.includes('land'))o.land+=q;else if(t.includes('creature'))o.creature+=q;else if(t.includes('instant'))o.instant+=q;else if(t.includes('sorcery'))o.sorcery+=q;else if(t.includes('artifact'))o.artifact+=q;else if(t.includes('enchantment'))o.enchantment+=q;else o.other+=q;}return o;}
function roleCount(d:Deck,roles:string[]){let n=0;for(const e of d.parsed.main){const c=card(d,e.name);if(!c)continue;const rs=new Set(inferCardRoles(c));if(roles.some(r=>rs.has(r)))n+=e.quantity;}return n;}
function trueProtection(d:Deck){let n=0;const names:string[]=[];for(const e of d.parsed.main){const c=card(d,e.name);if(!c)continue;const rs=new Set(inferCardRoles(c)),name=norm(e.name);if(rs.has('countermagic')||rs.has('free interaction')||rs.has('protection')||rs.has('board protection')||['silence','ranger-captain of eos',"dovin's veto","louisoix's sacrifice",'conqueror\'s flail'].includes(name)){n+=e.quantity;names.push(e.name);}}return{count:n,names};}
function retained(d:Deck,stock:Deck){const s=new Set(stock.parsed.main.map(e=>norm(e.name)));const names=d.parsed.main.filter(e=>s.has(norm(e.name))).map(e=>e.name);return{count:names.length,names};}
function tutors(d:Deck){const out:string[]=[];for(const e of d.parsed.main){const c=card(d,e.name);if(!c)continue;const rs=new Set(inferCardRoles(c));if(rs.has('tutor')||['ranger-captain of eos','delivery moogle','varragoth, bloodsky sire','search for dagger','praetor\'s grasp'].includes(norm(e.name)))out.push(e.name);}return out;}
function lowManaNonTriggers(d:Deck){const out:string[]=[];for(const e of d.parsed.main){const c=card(d,e.name);if(!c||/land/i.test(c.type_line)||/creature/i.test(c.type_line))continue;if(c.cmc<3)out.push(e.name);}return out;}
interface Signal{keep:number;uptime:number;protection:number;spells:number;draws:number;}
function signal(r:Record<string,unknown>):Signal{const b=rec(r.baseline),a=rec(r.advanced);return{keep:num(rec(b.openingHands).functionalKeepRate),uptime:num(rec(a.commanderPressure).battlefieldUptimePercent),protection:num(rec(a.interactionPressure).protectionWinRateWhenChallenged),spells:num(rec(a.cardFlow).averageSpellsCast),draws:num(rec(a.cardFlow).averageCardsDrawnByEffects)};}
function delta(a:Signal,b:Signal):Signal{return{keep:b.keep-a.keep,uptime:b.uptime-a.uptime,protection:b.protection-a.protection,spells:b.spells-a.spells,draws:b.draws-a.draws};}
function mean(v:Signal[]):Signal{return{keep:avg(v.map(x=>x.keep)),uptime:avg(v.map(x=>x.uptime)),protection:avg(v.map(x=>x.protection)),spells:avg(v.map(x=>x.spells)),draws:avg(v.map(x=>x.draws))};}
const scenarios:Array<{pressure:PodPressureV06;turns:number;seed:number}>=[{pressure:'upgraded',turns:5,seed:20260831},{pressure:'upgraded',turns:7,seed:20260917},{pressure:'optimized',turns:5,seed:20261001},{pressure:'optimized',turns:7,seed:20261031},{pressure:'cedh',turns:5,seed:20261129},{pressure:'cedh',turns:7,seed:20270111},{pressure:'cedh',turns:9,seed:20270223}];
function sim(d:Deck,s:{pressure:PodPressureV06;turns:number;seed:number}){return simulateDeckGameplayV06(d.parsed,d.cards,{iterations:2600,advancedIterations:2600,turns:s.turns,seed:s.seed,pressure:s.pressure}) as unknown as Record<string,unknown>;}
async function main(){const [aText,eText,sText]=await Promise.all([readFile(A11,'utf8'),readFile(EXT,'utf8'),readFile(STOCK,'utf8')]);const [a,e,s]=await Promise.all([resolve(aText),resolve(eText),resolve(sText)]);if(a.notFound.length||e.notFound.length)throw new Error(`Unresolved cards: A11=${a.notFound.join('|')} EXT=${e.notFound.join('|')}`);
const analyze=(d:Deck)=>({count:d.parsed.totalCards,legal:validateCommanderDeck(d.parsed,d.cards),types:typeCounts(d),metrics:buildDeckMetrics(d.parsed,d.cards),ystola:yOffers(d),stockRetained:retained(d,s),drawRoles:roleCount(d,['card draw','repeatable draw','card selection']),interactionRoles:roleCount(d,['spot interaction','countermagic','board wipe','free interaction']),protection:trueProtection(d),tutors:tutors(d),lowManaNonTriggers:lowManaNonTriggers(d)});
const aa=analyze(a),ee=analyze(e);const ds:Signal[]=[];const runs=[];for(const sc of scenarios){const av=signal(sim(a,sc)),ev=signal(sim(e,sc)),d=delta(av,ev);ds.push(d);runs.push({...sc,a11:av,external:ev,deltaExternalMinusA11:d});}const sd=mean(ds);
const report={a11:aa,external:ee,simulationExternalMinusA11:sd,runs,caveats:['Strategic comparison resolves Oracle names; it does not certify external list FF-printing compliance.','Free evoke is optimistic because pitch-card disadvantage is not fully charged.','Brainstorm-like effects can overstate raw effect-draw metrics.']};await writeFile('scions-external-comparison-v3.json',JSON.stringify(report,null,2));
const md=['# A11 vs External Y\'shtola — Strategic Comparison v3','',`A11 count/legal: ${aa.count}/${aa.legal.isLegal}; External: ${ee.count}/${ee.legal.isLegal}`,`Stock cards retained: A11 ${aa.stockRetained.count}; External ${ee.stockRetained.count}`,`Y'shtola opportunities: A11 ${aa.ystola.total} (${aa.ystola.instant} instant-speed); External ${ee.ystola.total} (${ee.ystola.instant} instant-speed)`,`Lands: A11 ${aa.metrics.landCount}; External ${ee.metrics.landCount}`,`Avg nonland MV: A11 ${aa.metrics.averageNonlandManaValue.toFixed(2)}; External ${ee.metrics.averageNonlandManaValue.toFixed(2)}`,`Ramp: A11 ${aa.metrics.rampCount}; External ${ee.metrics.rampCount}`,`Interaction roles: A11 ${aa.interactionRoles}; External ${ee.interactionRoles}`,`Protection/stack: A11 ${aa.protection.count}; External ${ee.protection.count}`,`Draw/selection roles: A11 ${aa.drawRoles}; External ${ee.drawRoles}`,`Tutors A11: ${aa.tutors.join(', ')}`,`Tutors External: ${ee.tutors.join(', ')}`,'',`External - A11 functional keep: ${sd.keep.toFixed(3)}`,`External - A11 commander uptime: ${sd.uptime.toFixed(3)}`,`External - A11 protection: ${sd.protection.toFixed(3)}`,`External - A11 spells cast: ${sd.spells.toFixed(3)}`,`External - A11 effect-draws: ${sd.draws.toFixed(3)}`,'',`External low-MV noncreature nontriggers: ${ee.lowManaNonTriggers.join(', ')}`,'','Caveat: printing compliance is intentionally separated from this run.',''].join('\n');await writeFile('scions-external-comparison-v3.md',md);console.log(md);}
await main();