import { readFile, writeFile } from 'node:fs/promises';
import type { ScryfallCard } from '../src/types/scryfall.js';
import { parseDecklist, buildDeckMetrics, type ParsedDeck } from '../src/services/deck.js';
import { getCardsByIdentifiers, getCardPrintings, inferCardRoles, type CardIdentifierInput } from '../src/services/scryfall.js';
import { printingMatchesPolicyV08, resolvePrintingPolicyV08 } from '../src/services/printing-policy-v08.js';
import { validateCommanderDeck } from '../src/services/commander-rules.js';
import { simulateDeckGameplayV06, type PodPressureV06 } from '../src/services/simulation-v06.js';

const A11='test-results/exploratory/scions-spellcraft-a11-control-deck.txt';
const EXT='test-results/exploratory/scions-spellcraft-external-comparison-deck.txt';
const STOCK='test-results/exploratory/scions-spellcraft-stock-deck.txt';
const AS_OF='2026-08-31';
const norm=(v:string)=>v.trim().toLowerCase();
const rec=(v:unknown):Record<string,unknown>=>v&&typeof v==='object'&&!Array.isArray(v)?v as Record<string,unknown>:{};
const num=(v:unknown)=>typeof v==='number'&&Number.isFinite(v)?v:0;
const avg=(v:number[])=>v.length?v.reduce((a,b)=>a+b,0)/v.length:0;
interface Deck{parsed:ParsedDeck;cards:ScryfallCard[];notFound:string[];}
function nameIds(p:ParsedDeck):CardIdentifierInput[]{return [...p.commanders,...p.main].map(e=>({name:e.name}));}
function exactIds(p:ParsedDeck):CardIdentifierInput[]{return [...p.commanders,...p.main].map(e=>({name:e.name,...(e.set?{set:e.set}:{}),...(e.collectorNumber?{collectorNumber:e.collectorNumber}:{})}));}
async function resolveNames(text:string):Promise<Deck>{const parsed=parseDecklist(text);const r=await getCardsByIdentifiers(nameIds(parsed));return{parsed,cards:r.cards,notFound:r.notFound};}
async function resolveExact(text:string):Promise<Deck>{const parsed=parseDecklist(text);const r=await getCardsByIdentifiers(exactIds(parsed));return{parsed,cards:r.cards,notFound:r.notFound};}
function card(d:Deck,name:string){return d.cards.find(c=>norm(c.name)===norm(name)||norm(c.name.split(' // ')[0]??'')===norm(name));}
function manaValueFromCost(cost:string){let total=0;for(const m of cost.matchAll(/\{([^}]+)\}/g)){const x=(m[1]??'').toUpperCase();if(/^\d+$/.test(x))total+=Number(x);else if(/^[WUBRGC]$/.test(x)||x.includes('/'))total+=1;}return total;}
function faceQualifies(f:{type_line?:string;mana_cost?:string},fallback:number){const t=(f.type_line??'').toLowerCase(),mv=f.mana_cost?manaValueFromCost(f.mana_cost):fallback;return !t.includes('creature')&&!t.includes('land')&&mv>=3;}
function yOffers(d:Deck){let total=0,instant=0;for(const e of d.parsed.main){const c=card(d,e.name);if(!c)continue;const faces=c.card_faces??[];const qualifyingFaces=faces.length?faces.filter(f=>faceQualifies(f,c.cmc)):(faceQualifies({type_line:c.type_line,mana_cost:c.mana_cost},c.cmc)?[{type_line:c.type_line}]:[]);if(qualifyingFaces.length){total+=e.quantity;if(qualifyingFaces.some(f=>(f.type_line??'').toLowerCase().includes('instant')))instant+=e.quantity;}}return{total,instant};}
function typeCounts(d:Deck){const out={land:0,creature:0,instant:0,sorcery:0,artifact:0,enchantment:0,other:0};for(const e of d.parsed.main){const c=card(d,e.name);if(!c)continue;const t=c.type_line.toLowerCase();const q=e.quantity;if(t.includes('land'))out.land+=q;else if(t.includes('creature'))out.creature+=q;else if(t.includes('instant'))out.instant+=q;else if(t.includes('sorcery'))out.sorcery+=q;else if(t.includes('artifact'))out.artifact+=q;else if(t.includes('enchantment'))out.enchantment+=q;else out.other+=q;}return out;}
function roleCount(d:Deck,roles:string[]){let n=0;for(const e of d.parsed.main){const c=card(d,e.name);if(!c)continue;const r=new Set(inferCardRoles(c));if(roles.some(x=>r.has(x)))n+=e.quantity;}return n;}
function trueProtection(d:Deck){let n=0;for(const e of d.parsed.main){const c=card(d,e.name);if(!c)continue;const r=new Set(inferCardRoles(c));const name=norm(e.name);if(r.has('countermagic')||r.has('free interaction')||r.has('protection')||r.has('board protection')||['silence','ranger-captain of eos','dovin\'s veto'].includes(name))n+=e.quantity;}return n;}
function retainedFromStock(d:Deck,stock:Deck){const s=new Set(stock.parsed.main.map(e=>norm(e.name)));return d.parsed.main.reduce((n,e)=>n+(s.has(norm(e.name))?e.quantity:0),0);}
function tutorNames(d:Deck){const result:string[]=[];for(const e of d.parsed.main){const c=card(d,e.name);if(!c)continue;const r=new Set(inferCardRoles(c));if(r.has('tutor')||['ranger-captain of eos','delivery moogle','v arragoth, bloodsky sire'.replace(' ','')].includes(norm(e.name).replace(' ','')))result.push(e.name);}return result;}
interface Signal{keep:number;uptime:number;protection:number;spells:number;draws:number;}
function signal(r:Record<string,unknown>):Signal{const b=rec(r.baseline),a=rec(r.advanced);return{keep:num(rec(b.openingHands).functionalKeepRate),uptime:num(rec(a.commanderPressure).battlefieldUptimePercent),protection:num(rec(a.interactionPressure).protectionWinRateWhenChallenged),spells:num(rec(a.cardFlow).averageSpellsCast),draws:num(rec(a.cardFlow).averageCardsDrawnByEffects)};}
function delta(a:Signal,b:Signal):Signal{return{keep:b.keep-a.keep,uptime:b.uptime-a.uptime,protection:b.protection-a.protection,spells:b.spells-a.spells,draws:b.draws-a.draws};}
function mean(v:Signal[]):Signal{return{keep:avg(v.map(x=>x.keep)),uptime:avg(v.map(x=>x.uptime)),protection:avg(v.map(x=>x.protection)),spells:avg(v.map(x=>x.spells)),draws:avg(v.map(x=>x.draws))};}
const scenarios:Array<{pressure:PodPressureV06;turns:number;seed:number}>=[{pressure:'upgraded',turns:5,seed:20260831},{pressure:'upgraded',turns:7,seed:20260917},{pressure:'optimized',turns:5,seed:20261001},{pressure:'optimized',turns:7,seed:20261031},{pressure:'cedh',turns:5,seed:20261129},{pressure:'cedh',turns:7,seed:20270111},{pressure:'cedh',turns:9,seed:20270223}];
function sim(d:Deck,s:{pressure:PodPressureV06;turns:number;seed:number}){return simulateDeckGameplayV06(d.parsed,d.cards,{iterations:2200,advancedIterations:2200,turns:s.turns,seed:s.seed,pressure:s.pressure}) as unknown as Record<string,unknown>;}
async function ffEligibility(d:Deck){const policy=await resolvePrintingPolicyV08({printingFamily:'Final Fantasy',includePromos:true,includeSpecialReleases:true});const missing:string[]=[];const eligible:Record<string,string[] >={};for(const name of [...new Set([...d.parsed.commanders,...d.parsed.main].map(e=>e.name))]){const ps=await getCardPrintings(name,250);const ok=ps.filter(c=>printingMatchesPolicyV08(c,policy,AS_OF));if(!ok.length)missing.push(name);else eligible[name]=[...new Set(ok.map(c=>c.set.toUpperCase()))];}return{missing,eligibleCount:Object.keys(eligible).length,totalUnique:new Set([...d.parsed.commanders,...d.parsed.main].map(e=>e.name)).size};}
async function main(){
 const [aText,eText,sText]=await Promise.all([readFile(A11,'utf8'),readFile(EXT,'utf8'),readFile(STOCK,'utf8')]);
 const [a,e,s,eExact]=await Promise.all([resolveNames(aText),resolveNames(eText),resolveNames(sText),resolveExact(eText)]);
 const policy=await resolvePrintingPolicyV08({printingFamily:'Final Fantasy',includePromos:true,includeSpecialReleases:true});
 const extFF=await ffEligibility(e);const exactFF=eExact.cards.filter(c=>printingMatchesPolicyV08(c,policy,AS_OF)).length;
 const analyze=(d:Deck)=>({count:d.parsed.totalCards,legal:validateCommanderDeck(d.parsed,d.cards),types:typeCounts(d),metrics:buildDeckMetrics(d.parsed,d.cards),ystola:yOffers(d),stockRetained:retainedFromStock(d,s),drawRoles:roleCount(d,['card draw','repeatable draw','card selection']),interactionRoles:roleCount(d,['spot interaction','countermagic','board wipe','free interaction']),trueProtection:trueProtection(d),tutors:tutorNames(d),combo:{whiteMage:d.parsed.main.some(x=>norm(x.name)==='the destined white mage'),ballista:d.parsed.main.some(x=>norm(x.name)==='walking ballista'),intent:d.parsed.main.some(x=>norm(x.name)==='diabolic intent'),ranger:d.parsed.main.some(x=>norm(x.name)==='ranger-captain of eos')}});
 const aa=analyze(a),ee=analyze(e);const ds:Signal[]=[];const runs=[];for(const sc of scenarios){const x=signal(sim(a,sc)),y=signal(sim(e,sc)),d=delta(x,y);ds.push(d);runs.push({...sc,a11:x,external:y,deltaExternalMinusA11:d});}const md=mean(ds);
 const report={a11:aa,external:ee,externalPrinting:{exactCardsResolved:eExact.cards.length,exactNotFound:eExact.notFound,exactFFPolicyCards:exactFF,oracleNamesWithNoEligibleFFPrinting:extFF.missing,oracleEligibleCount:extFF.eligibleCount,totalUnique:extFF.totalUnique},simulationExternalMinusA11:md,runs,caveats:['External list simulation resolves cards by Oracle name so strategic comparison is not distorted by non-FF exact printings.','Evoke/free-alternative simulation does not fully charge pitch-card disadvantage, so Grief/Solitude/Subtlety can be overstated.','Brainstorm-like selection may be overstated by raw effect-draw metrics.']};
 await writeFile('scions-external-comparison.json',JSON.stringify(report,null,2));
 const mdText=['# Scions A11 vs External Y\'shtola Build','',`A11 cards: ${aa.count}; External cards: ${ee.count}`,`A11 legal: ${aa.legal.isLegal}; External legal by Oracle names: ${ee.legal.isLegal}`,'',`A11 stock cards retained: ${aa.stockRetained}; External stock cards retained: ${ee.stockRetained}`,`A11 Y\'shtola opportunities: ${aa.ystola.total} (${aa.ystola.instant} instant-speed); External: ${ee.ystola.total} (${ee.ystola.instant} instant-speed)`,`A11 lands: ${aa.metrics.landCount}; External lands: ${ee.metrics.landCount}`,`A11 avg nonland MV: ${aa.metrics.averageNonlandManaValue.toFixed(2)}; External: ${ee.metrics.averageNonlandManaValue.toFixed(2)}`,`A11 ramp: ${aa.metrics.rampCount}; External: ${ee.metrics.rampCount}`,`A11 interaction roles: ${aa.interactionRoles}; External: ${ee.interactionRoles}`,`A11 true protection/stack count: ${aa.trueProtection}; External: ${ee.trueProtection}`,`A11 draw/selection roles: ${aa.drawRoles}; External: ${ee.drawRoles}`,'',`External exact listed printings satisfying FF policy: ${exactFF}/${eExact.cards.length}`,`External Oracle names with NO eligible FF printing (${extFF.missing.length}): ${extFF.missing.join(', ')||'none'}`,'',`Mean external - A11 functional keep: ${md.keep.toFixed(3)}`,`Mean external - A11 commander uptime: ${md.uptime.toFixed(3)}`,`Mean external - A11 protection: ${md.protection.toFixed(3)}`,`Mean external - A11 spells cast: ${md.spells.toFixed(3)}`,`Mean external - A11 effect-draws: ${md.draws.toFixed(3)}`,'','Caveat: free evoke and Brainstorm-style effects are optimistic in the current simulator.',''].join('\n');await writeFile('scions-external-comparison.md',mdText);console.log(mdText);
}
await main();