import { readFile, writeFile } from 'node:fs/promises';
import type { ScryfallCard } from '../src/types/scryfall.js';
import { parseDecklist, buildDeckMetrics, type ParsedDeck } from '../src/services/deck.js';
import { getCardsByIdentifiers, getCardPrintings, inferCardRoles, type CardIdentifierInput } from '../src/services/scryfall.js';
import { printingMatchesPolicyV08, resolvePrintingPolicyV08 } from '../src/services/printing-policy-v08.js';
import { validateCommanderDeck } from '../src/services/commander-rules.js';
import { simulateDeckGameplayV06, type PodPressureV06 } from '../src/services/simulation-v06.js';

const A11='test-results/exploratory/scions-spellcraft-a11-control-deck.txt';
const EXT='test-results/exploratory/scions-spellcraft-external-comparison-deck.txt';
const STOCK='test-results/exploratory/scions-spellcraft-stock-deck.txt';
const AS_OF='2026-08-31';
const sleep=(ms:number)=>new Promise(r=>setTimeout(r,ms));
const norm=(v:string)=>v.trim().toLowerCase();
const rec=(v:unknown):Record<string,unknown>=>v&&typeof v==='object'&&!Array.isArray(v)?v as Record<string,unknown>:{};
const num=(v:unknown)=>typeof v==='number'&&Number.isFinite(v)?v:0;
const avg=(v:number[])=>v.length?v.reduce((a,b)=>a+b,0)/v.length:0;
interface Deck{parsed:ParsedDeck;cards:ScryfallCard[];notFound:string[];}
function ids(p:ParsedDeck,exact=false):CardIdentifierInput[]{return [...p.commanders,...p.main].map(e=>({name:e.name,...(exact&&e.set?{set:e.set}:{}),...(exact&&e.collectorNumber?{collectorNumber:e.collectorNumber}:{})}));}
async function resolve(text:string,exact=false):Promise<Deck>{const parsed=parseDecklist(text);const r=await getCardsByIdentifiers(ids(parsed,exact));return{parsed,cards:r.cards,notFound:r.notFound};}
function card(d:Deck,name:string){return d.cards.find(c=>norm(c.name)===norm(name)||norm(c.name.split(' // ')[0]??'')===norm(name));}
function mv(cost:string){let n=0;for(const m of cost.matchAll(/\{([^}]+)\}/g)){const x=(m[1]??'').toUpperCase();if(/^\d+$/.test(x))n+=Number(x);else if(/^[WUBRGC]$/.test(x)||x.includes('/'))n+=1;}return n;}
function qualifies(type:string|undefined,cost:string|undefined,fallback:number){const t=(type??'').toLowerCase();return !t.includes('creature')&&!t.includes('land')&&(cost?mv(cost):fallback)>=3;}
function yOffers(d:Deck){let total=0,instant=0;for(const e of d.parsed.main){const c=card(d,e.name);if(!c)continue;const faces=c.card_faces??[];if(faces.length){const q=faces.filter(f=>qualifies(f.type_line,f.mana_cost,c.cmc));if(q.length){total+=e.quantity;if(q.some(f=>(f.type_line??'').toLowerCase().includes('instant')))instant+=e.quantity;}}else if(qualifies(c.type_line,c.mana_cost,c.cmc)){total+=e.quantity;if(c.type_line.toLowerCase().includes('instant'))instant+=e.quantity;}}return{total,instant};}
function typeCounts(d:Deck){const o={land:0,creature:0,instant:0,sorcery:0,artifact:0,enchantment:0,other:0};for(const e of d.parsed.main){const c=card(d,e.name);if(!c)continue;const t=c.type_line.toLowerCase(),q=e.quantity;if(t.includes('land'))o.land+=q;else if(t.includes('creature'))o.creature+=q;else if(t.includes('instant'))o.instant+=q;else if(t.includes('sorcery'))o.sorcery+=q;else if(t.includes('artifact'))o.artifact+=q;else if(t.includes('enchantment'))o.enchantment+=q;else o.other+=q;}return o;}
function roleCount(d:Deck,roles:string[]){let n=0;for(const e of d.parsed.main){const c=card(d,e.name);if(!c)continue;const rs=new Set(inferCardRoles(c));if(roles.some(r=>rs.has(r)))n+=e.quantity;}return n;}
function trueProtection(d:Deck){let n=0;for(const e of d.parsed.main){const c=card(d,e.name);if(!c)continue;const rs=new Set(inferCardRoles(c)),name=norm(e.name);if(rs.has('countermagic')||rs.has('free interaction')||rs.has('protection')||rs.has('board protection')||['silence','ranger-captain of eos',"dovin's veto",'louisoix\'s sacrifice'].includes(name))n+=e.quantity;}return n;}
function retained(d:Deck,stock:Deck){const s=new Set(stock.parsed.main.map(e=>norm(e.name)));return d.parsed.main.reduce((n,e)=>n+(s.has(norm(e.name))?e.quantity:0),0);}
function tutors(d:Deck){const out:string[]=[];for(const e of d.parsed.main){const c=card(d,e.name);if(!c)continue;const rs=new Set(inferCardRoles(c));if(rs.has('tutor')||['ranger-captain of eos','delivery moogle','varragoth, bloodsky sire','search for dagger'].includes(norm(e.name)))out.push(e.name);}return out;}
interface Signal{keep:number;uptime:number;protection:number;spells:number;draws:number;}
function signal(r:Record<string,unknown>):Signal{const b=rec(r.baseline),a=rec(r.advanced);return{keep:num(rec(b.openingHands).functionalKeepRate),uptime:num(rec(a.commanderPressure).battlefieldUptimePercent),protection:num(rec(a.interactionPressure).protectionWinRateWhenChallenged),spells:num(rec(a.cardFlow).averageSpellsCast),draws:num(rec(a.cardFlow).averageCardsDrawnByEffects)};}
function delta(a:Signal,b:Signal):Signal{return{keep:b.keep-a.keep,uptime:b.uptime-a.uptime,protection:b.protection-a.protection,spells:b.spells-a.spells,draws:b.draws-a.draws};}
function mean(v:Signal[]):Signal{return{keep:avg(v.map(x=>x.keep)),uptime:avg(v.map(x=>x.uptime)),protection:avg(v.map(x=>x.protection)),spells:avg(v.map(x=>x.spells)),draws:avg(v.map(x=>x.draws))};}
const scenarios:Array<{pressure:PodPressureV06;turns:number;seed:number}>=[{pressure:'upgraded',turns:5,seed:20260831},{pressure:'upgraded',turns:7,seed:20260917},{pressure:'optimized',turns:5,seed:20261001},{pressure:'optimized',turns:7,seed:20261031},{pressure:'cedh',turns:5,seed:20261129},{pressure:'cedh',turns:7,seed:20270111},{pressure:'cedh',turns:9,seed:20270223}];
function sim(d:Deck,s:{pressure:PodPressureV06;turns:number;seed:number}){return simulateDeckGameplayV06(d.parsed,d.cards,{iterations:2200,advancedIterations:2200,turns:s.turns,seed:s.seed,pressure:s.pressure}) as unknown as Record<string,unknown>;}
async function ffEligibility(d:Deck,policy:Awaited<ReturnType<typeof resolvePrintingPolicyV08>>){const missing:string[]=[];const eligible:Record<string,string[]>={};const names=[...new Set([...d.parsed.commanders,...d.parsed.main].map(e=>e.name))];await sleep(1500);for(const name of names){await sleep(350);const ps=await getCardPrintings(name,250);const ok=ps.filter(c=>printingMatchesPolicyV08(c,policy,AS_OF));if(ok.length)eligible[name]=[...new Set(ok.map(c=>c.set.toUpperCase()))];else missing.push(name);}return{missing,eligibleCount:Object.keys(eligible).length,totalUnique:names.length};}
async function main(){const [aText,eText,sText]=await Promise.all([readFile(A11,'utf8'),readFile(EXT,'utf8'),readFile(STOCK,'utf8')]);const [a,e,s,eExact]=await Promise.all([resolve(aText),resolve(eText),resolve(sText),resolve(eText,true)]);const policy=await resolvePrintingPolicyV08({printingFamily:'Final Fantasy',includePromos:true,includeSpecialReleases:true});
const analyze=(d:Deck)=>({count:d.parsed.totalCards,legal:validateCommanderDeck(d.parsed,d.cards),types:typeCounts(d),metrics:buildDeckMetrics(d.parsed,d.cards),ystola:yOffers(d),stockRetained:retained(d,s),drawRoles:roleCount(d,['card draw','repeatable draw','card selection']),interactionRoles:roleCount(d,['spot interaction','countermagic','board wipe','free interaction']),trueProtection:trueProtection(d),tutors:tutors(d)});
const aa=analyze(a),ee=analyze(e);const ds:Signal[]=[];const runs=[];for(const sc of scenarios){const av=signal(sim(a,sc)),ev=signal(sim(e,sc)),d=delta(av,ev);ds.push(d);runs.push({...sc,a11:av,external:ev,deltaExternalMinusA11:d});}const simDelta=mean(ds);
const extFF=await ffEligibility(e,policy);const exactFF=eExact.cards.filter(c=>printingMatchesPolicyV08(c,policy,AS_OF)).length;
const report={a11:aa,external:ee,externalPrinting:{exactCardsResolved:eExact.cards.length,exactNotFound:eExact.notFound,exactFFPolicyCards:exactFF,oracleNamesWithNoEligibleFFPrinting:extFF.missing,oracleEligibleCount:extFF.eligibleCount,totalUnique:extFF.totalUnique},simulationExternalMinusA11:simDelta,runs,caveats:['External strategy resolves by Oracle name.','Evoke/free-alternative simulator does not fully charge pitch-card disadvantage.','Brainstorm-style selection can overstate effect-draw.']};await writeFile('scions-external-comparison-v2.json',JSON.stringify(report,null,2));
const md=['# A11 vs External Y\'shtola — Comparison v2','',`A11 count/legal: ${aa.count}/${aa.legal.isLegal}; External: ${ee.count}/${ee.legal.isLegal}`,`Stock retained: A11 ${aa.stockRetained}; External ${ee.stockRetained}`,`Y'shtola opportunities: A11 ${aa.ystola.total} (${aa.ystola.instant} instant-speed); External ${ee.ystola.total} (${ee.ystola.instant})`,`Lands: A11 ${aa.metrics.landCount}; External ${ee.metrics.landCount}`,`Avg nonland MV: A11 ${aa.metrics.averageNonlandManaValue.toFixed(2)}; External ${ee.metrics.averageNonlandManaValue.toFixed(2)}`,`Ramp: A11 ${aa.metrics.rampCount}; External ${ee.metrics.rampCount}`,`Interaction roles: A11 ${aa.interactionRoles}; External ${ee.interactionRoles}`,`True protection/stack: A11 ${aa.trueProtection}; External ${ee.trueProtection}`,`Draw/selection roles: A11 ${aa.drawRoles}; External ${ee.drawRoles}`,`Tutors A11: ${aa.tutors.join(', ')}`,`Tutors External: ${ee.tutors.join(', ')}`,'',`External exact listed FF-policy printings: ${exactFF}/${eExact.cards.length}`,`External Oracle names without any eligible FF printing (${extFF.missing.length}): ${extFF.missing.join(', ')||'none'}`,'',`External - A11 keep: ${simDelta.keep.toFixed(3)}`,`External - A11 uptime: ${simDelta.uptime.toFixed(3)}`,`External - A11 protection: ${simDelta.protection.toFixed(3)}`,`External - A11 spells: ${simDelta.spells.toFixed(3)}`,`External - A11 effect-draws: ${simDelta.draws.toFixed(3)}`,''].join('\n');await writeFile('scions-external-comparison-v2.md',md);console.log(md);}
await main();