import { readFile, writeFile } from 'node:fs/promises';
import type { ScryfallCard } from '../src/types/scryfall.js';
import { comboAccessQualityV15 } from '../src/services/combo-access-quality-v15.js';
import { validateCommanderDeck } from '../src/services/commander-rules.js';
import { buildDeckMetrics, parseDecklist, type ParsedDeck } from '../src/services/deck.js';
import { printingMatchesPolicyV08, resolvePrintingPolicyV08 } from '../src/services/printing-policy-v08.js';
import { getCardsByIdentifiers, type CardIdentifierInput } from '../src/services/scryfall.js';
import { simulateDeckGameplayV06, type PodPressureV06 } from '../src/services/simulation-v06.js';
import { BRACKET_FIVE_AUTHORITATIVE_TARGETS_V15, BRACKET_FIVE_AVERAGE_NONLAND_MV_MAX_V15, minimumPersistentColoredManaSourcesV15 } from '../src/services/upgrade.js';

const BASE='test-results/exploratory/counter-blitz-a22d-synergy-repair-deck.txt';
const OUT='test-results/exploratory/counter-blitz-a23-synergy-checkpoint-deck.txt';
const SIDEQUEST='Sidequest: Raise a Chocobo // Black Chocobo';
const SWAPS=[
 [SIDEQUEST,'1 Yuna, Grand Summoner (FIC) 8'],
 ['Key to the City','1 Resourceful Defense (FIC) 251'],
] as const;
const ROUTES=[['The Destined White Mage','Walking Ballista'],['Gatta and Luzzu','Hardened Scales','Walking Ballista'],['Gatta and Luzzu','The Earth Crystal','Walking Ballista']] as const;
const PIECES=['The Destined White Mage','Walking Ballista','Gatta and Luzzu','Hardened Scales','The Earth Crystal'] as const;
const SCENARIOS:Array<{pressure:PodPressureV06;turns:number;seed:number}>=[
 {pressure:'upgraded',turns:5,seed:20260831},{pressure:'upgraded',turns:7,seed:20260907},{pressure:'optimized',turns:5,seed:20260921},{pressure:'optimized',turns:7,seed:20261013},{pressure:'cedh',turns:5,seed:20261109},{pressure:'cedh',turns:7,seed:20261215},{pressure:'cedh',turns:9,seed:20270125},
];
const norm=(v:string)=>v.trim().toLocaleLowerCase();
const rec=(v:unknown):Record<string,unknown>=>v&&typeof v==='object'&&!Array.isArray(v)?v as Record<string,unknown>:{};
const num=(v:unknown)=>typeof v==='number'&&Number.isFinite(v)?v:0;
const avg=(v:readonly number[])=>v.length?v.reduce((a,b)=>a+b,0)/v.length:0;
function ids(p:ParsedDeck):CardIdentifierInput[]{return[...p.commanders,...p.main].map(e=>({name:e.name,...(e.set?{set:e.set}:{}),...(e.collectorNumber?{collectorNumber:e.collectorNumber}:{})}));}
async function resolve(text:string){const parsed=parseDecklist(text);const r=await getCardsByIdentifiers(ids(parsed));return{parsed,cards:r.cards,notFound:r.notFound};}
function identity(p:ParsedDeck,c:readonly ScryfallCard[]):string[]{const n=new Set(p.commanders.map(e=>norm(e.name)));return[...new Set(c.filter(x=>n.has(norm(x.name))).flatMap(x=>x.color_identity))].sort();}
function apply(text:string):string{const lines=text.split(/\r?\n/);for(const[cut,add]of SWAPS){const i=lines.findIndex(l=>l.startsWith(`1 ${cut} (`));if(i<0)throw new Error(`Missing cut ${cut}`);lines[i]=add;}return lines.join('\n');}
interface Signal{keep:number;uptime:number;protection:number;spells:number;draws:number;white:number;gattaScales:number;gattaCrystal:number;}
function signal(r:Record<string,unknown>,turns:number):Signal{const b=rec(r.baseline),a=rec(r.advanced),cs=Array.isArray(a.combos)?a.combos.map(rec):[],k=`turn${turns}`,ready=cs.map(c=>num(rec(c.allNamedPiecesInHandOrBattlefieldByTurn)[k]));return{keep:num(rec(b.openingHands).functionalKeepRate),uptime:num(rec(a.commanderPressure).battlefieldUptimePercent),protection:num(rec(a.interactionPressure).protectionWinRateWhenChallenged),spells:num(rec(a.cardFlow).averageSpellsCast),draws:num(rec(a.cardFlow).averageCardsDrawnByEffects),white:ready[0]??0,gattaScales:ready[1]??0,gattaCrystal:ready[2]??0};}
function delta(b:Signal,a:Signal):Signal{return{keep:a.keep-b.keep,uptime:a.uptime-b.uptime,protection:a.protection-b.protection,spells:a.spells-b.spells,draws:a.draws-b.draws,white:a.white-b.white,gattaScales:a.gattaScales-b.gattaScales,gattaCrystal:a.gattaCrystal-b.gattaCrystal};}
function mean(v:readonly Signal[]):Signal{return{keep:avg(v.map(x=>x.keep)),uptime:avg(v.map(x=>x.uptime)),protection:avg(v.map(x=>x.protection)),spells:avg(v.map(x=>x.spells)),draws:avg(v.map(x=>x.draws)),white:avg(v.map(x=>x.white)),gattaScales:avg(v.map(x=>x.gattaScales)),gattaCrystal:avg(v.map(x=>x.gattaCrystal))};}
function sim(p:ParsedDeck,c:ScryfallCard[],s:{pressure:PodPressureV06;turns:number;seed:number}):Record<string,unknown>{return simulateDeckGameplayV06(p,c,{iterations:1800,advancedIterations:1800,turns:s.turns,seed:s.seed,pressure:s.pressure,comboPieces:ROUTES}) as unknown as Record<string,unknown>;}
function correctedA22d(p:ParsedDeck,m:ReturnType<typeof buildDeckMetrics>){const has=p.main.some(e=>norm(e.name)===norm(SIDEQUEST));return{ramp:m.rampCount-(has?1:0),colored:m.persistentColoredManaSourceCount-(has?1:0),cheap:m.cheapInteractionCount+(p.main.some(e=>norm(e.name)===norm("Dovin's Veto"))?1:0)};}
function correctedA23(p:ParsedDeck,m:ReturnType<typeof buildDeckMetrics>){return{ramp:m.rampCount,colored:m.persistentColoredManaSourceCount,cheap:m.cheapInteractionCount+(p.main.some(e=>norm(e.name)===norm("Dovin's Veto"))?1:0)};}

async function main():Promise<void>{
 console.log('COUNTER BLITZ A23 SYNERGY CHECKPOINT');
 const baseText=await readFile(BASE,'utf8');const nextText=apply(baseText);const [base,next]=await Promise.all([resolve(baseText),resolve(nextText)]);const failures:string[]=[];const policy=await resolvePrintingPolicyV08({printingFamily:'Final Fantasy',includePromos:true,includeSpecialReleases:true});
 for(const[label,state]of[['A22d',base],['A23',next]] as const){if(state.notFound.length)failures.push(`${label}:unresolved`);if(state.parsed.totalCards!==100)failures.push(`${label}:count`);if(!validateCommanderDeck(state.parsed,state.cards).isLegal)failures.push(`${label}:illegal`);if(!state.cards.every(c=>printingMatchesPolicyV08(c,policy)))failures.push(`${label}:FF-policy`);}
 const before=new Set(base.parsed.main.map(e=>norm(e.name))),after=new Set(next.parsed.main.map(e=>norm(e.name)));for(const[cut,addLine]of SWAPS){const add=addLine.replace(/^1\s+/,'').replace(/\s+\([^)]+\)\s+\S+$/,'');if(!before.has(norm(cut))||after.has(norm(cut)))failures.push(`bad-cut:${cut}`);if(before.has(norm(add))||!after.has(norm(add)))failures.push(`bad-add:${add}`);}
 const m0=buildDeckMetrics(base.parsed,base.cards),m1=buildDeckMetrics(next.parsed,next.cards),c0=correctedA22d(base.parsed,m0),c1=correctedA23(next.parsed,m1),colors=identity(next.parsed,next.cards).length;
 if(m1.averageNonlandManaValue>BRACKET_FIVE_AVERAGE_NONLAND_MV_MAX_V15)failures.push('structural:mv');if(m1.earlyPlayCount<BRACKET_FIVE_AUTHORITATIVE_TARGETS_V15.earlyPlays)failures.push('structural:early');if(m1.fastManaCount<BRACKET_FIVE_AUTHORITATIVE_TARGETS_V15.fastMana)failures.push('structural:fast-mana');if(Number(m1.roleCounts['free interaction']??0)<BRACKET_FIVE_AUTHORITATIVE_TARGETS_V15.freeInteraction)failures.push('structural:free-interaction');if(c1.ramp<c0.ramp)failures.push('structural:corrected-ramp-regression');if(c1.colored<minimumPersistentColoredManaSourcesV15(colors))failures.push(`structural:corrected-colored-${c1.colored}`);if(c1.cheap<BRACKET_FIVE_AUTHORITATIVE_TARGETS_V15.cheapInteraction)failures.push(`structural:corrected-cheap-${c1.cheap}`);
 const pieces=PIECES.map(n=>next.cards.find(c=>norm(c.name)===norm(n))).filter((c):c is ScryfallCard=>Boolean(c));if(pieces.length!==PIECES.length)failures.push('combo-pieces-unresolved');const comboAccess=pieces.length===PIECES.length?comboAccessQualityV15(next.cards,pieces):null;
 const ds:Signal[]=[];const scenarios:Array<Record<string,unknown>>=[];for(const s of SCENARIOS){const b=signal(sim(base.parsed,base.cards,s),s.turns),a=signal(sim(next.parsed,next.cards,s),s.turns),d=delta(b,a);ds.push(d);scenarios.push({...s,before:b,after:a,delta:d});}const d=mean(ds);if(d.keep<-2.25)failures.push('sim:keep');if(d.uptime<-3.5)failures.push('sim:uptime');if(d.protection<-8)failures.push('sim:protection');if(d.spells<-0.24)failures.push('sim:spells');if(d.draws<-0.45)failures.push('sim:draws');if(d.white<-3.5||d.gattaScales<-3.5||d.gattaCrystal<-3.5)failures.push('sim:combo-route');
 const report={status:failures.length?'REVIEW':'PASS',swaps:[{cut:SIDEQUEST,add:'Yuna, Grand Summoner'},{cut:'Key to the City',add:'Resourceful Defense'}],failures,semanticCorrection:'A22d Sidequest backside land-search is not functional ramp in this list because the four-Bird transform condition is unsupported.',metrics:{a22dRaw:{mv:m0.averageNonlandManaValue,early:m0.earlyPlayCount,ramp:m0.rampCount,colored:m0.persistentColoredManaSourceCount,cheap:m0.cheapInteractionCount},a22dCorrected:c0,a23:{mv:m1.averageNonlandManaValue,early:m1.earlyPlayCount,ramp:m1.rampCount,colored:m1.persistentColoredManaSourceCount,correctedCheap:c1.cheap}},comboAccess,meanDelta:d,scenarios,boundary:'Simulation is a regression guard. Manual Tidus/counter synergy remains authoritative.'};await writeFile('counter-blitz-a23-synergy-checkpoint.json',JSON.stringify(report,null,2));await writeFile(OUT,nextText);
 const md=['# Counter Blitz A23 — Synergy Checkpoint','',`- Result: **${report.status}**`,`- Failures: ${failures.length?failures.join('; '):'none'}`,'','## Swaps','',`- ${SIDEQUEST} -> Yuna, Grand Summoner`,'- Key to the City -> Resourceful Defense','',`- A22d corrected functional ramp/colored: ${c0.ramp}/${c0.colored}`,`- A23 functional ramp/colored: ${c1.ramp}/${c1.colored}`,`- A23 average nonland MV: ${m1.averageNonlandManaValue.toFixed(3)}`,`- A23 early plays: ${m1.earlyPlayCount}`,`- Corrected cheap interaction: ${c1.cheap}`,`- Combo access score: ${comboAccess?.weightedScore ?? 'n/a'}`,`- Mean Δ spells: ${d.spells.toFixed(3)}`,`- Mean Δ draws: ${d.draws.toFixed(3)}`,`- Mean Δ commander uptime: ${d.uptime.toFixed(3)}`,`- Mean Δ protection: ${d.protection.toFixed(3)}`,`- Mean Δ White Mage route: ${d.white.toFixed(3)}`,`- Mean Δ Gatta/Scales route: ${d.gattaScales.toFixed(3)}`,`- Mean Δ Gatta/Earth Crystal route: ${d.gattaCrystal.toFixed(3)}`,'','Semantic correction: A22d Sidequest was falsely credited as reliable ramp/colored mana because role inference reads the back-face land-search without testing the four-Bird transform requirement.',''].join('\n');await writeFile('counter-blitz-a23-synergy-checkpoint.md',md);console.log(md);if(failures.length)process.exitCode=1;
}
await main();
