import { readFile, writeFile } from 'node:fs/promises';
import type { ScryfallCard } from '../src/types/scryfall.js';
import { validateCommanderDeck } from '../src/services/commander-rules.js';
import { buildDeckMetrics, parseDecklist, type ParsedDeck } from '../src/services/deck.js';
import { printingMatchesPolicyV08, resolvePrintingPolicyV08 } from '../src/services/printing-policy-v08.js';
import { getCardsByIdentifiers, type CardIdentifierInput } from '../src/services/scryfall.js';
import { simulateDeckGameplayV06, type PodPressureV06 } from '../src/services/simulation-v06.js';
const DECK='test-results/exploratory/scions-spellcraft-a5-deck.txt',AS_OF='2026-08-31';
type C={name:string;set:string;collector:string};type T={id:string;cut:string;add:C;manual:string};
const C={toxic:{name:'Toxic Deluge',set:'SLD',collector:'1860'},stroke:{name:'Stroke of Midnight',set:'FCA',collector:'26'},ending:{name:'Prismatic Ending',set:'SLD',collector:'1868'},grasp:{name:"Praetor's Grasp",set:'SLD',collector:'1861'},citadel:{name:"Bolas's Citadel",set:'FCA',collector:'7'}} as const;
const TESTS:T[]=[
{id:'crux_to_toxic',cut:'Crux of Fate',add:C.toxic,manual:'MV3 Ystola-triggering -X/-X wipe; keeps trigger while lowering curve'},
{id:'final_to_toxic',cut:'Final Judgment',add:C.toxic,manual:'trade exile wipe for efficient MV3 -X/-X wipe'},
{id:'nova_to_toxic',cut:'Cleansing Nova',add:C.toxic,manual:'trade modal artifact/enchantment option for efficient MV3 wipe'},
{id:'vindicate_to_stroke',cut:'Vindicate',add:C.stroke,manual:'same MV3 trigger; lose land targeting, gain instant speed'},
{id:'vindicate_to_ending',cut:'Vindicate',add:C.ending,manual:'variable exile removal; can trigger Ystola at X>=2, limited by Esper converge'},
{id:'rite_to_grasp',cut:'Rite of Replication',add:C.grasp,manual:'trade clone finisher for MV3 opponent-library disruption/value'},
{id:'reaper_to_grasp',cut:"Reaper's Scythe",add:C.grasp,manual:'replace combat equipment with MV3 disruptive spell'},
{id:'tome_to_grasp',cut:'Tome of Legends',add:C.grasp,manual:'trade slow draw for MV3 disruptive card access'},
{id:'jewel_to_citadel',cut:'Coveted Jewel',add:C.citadel,manual:'same MV6 Ystola trigger; trade immediate draw/ramp for top-library casting engine and finisher'},
];
const SC:Array<{pressure:PodPressureV06;turns:number;seed:number}>=[{pressure:'upgraded',turns:5,seed:20260831},{pressure:'upgraded',turns:7,seed:20260915},{pressure:'optimized',turns:5,seed:20261001},{pressure:'optimized',turns:7,seed:20261031},{pressure:'cedh',turns:5,seed:20261123},{pressure:'cedh',turns:7,seed:20261231},{pressure:'cedh',turns:9,seed:20270213}];
const norm=(v:string)=>v.trim().toLowerCase(),rec=(v:unknown):Record<string,unknown>=>v&&typeof v==='object'&&!Array.isArray(v)?v as Record<string,unknown>:{},num=(v:unknown)=>typeof v==='number'&&Number.isFinite(v)?v:0,avg=(v:number[])=>v.reduce((a,b)=>a+b,0)/v.length;
interface D{parsed:ParsedDeck;cards:ScryfallCard[];text:string;}function ids(p:ParsedDeck):CardIdentifierInput[]{return[...p.commanders,...p.main].map(e=>({name:e.name,...(e.set?{set:e.set}:{}),...(e.collectorNumber?{collectorNumber:e.collectorNumber}:{})}));}async function resolve(text:string):Promise<D>{const p=parseDecklist(text),r=await getCardsByIdentifiers(ids(p));if(r.notFound.length)throw new Error(`unresolved:${r.notFound.join('|')}`);return{parsed:p,cards:r.cards,text};}function replace(text:string,t:T){const lines=text.split('\n'),i=lines.findIndex(l=>l.startsWith('1 ')&&norm(l.replace(/^1\s+/, '').replace(/\s+\([A-Z0-9]+\)\s+\S+\s*$/,''))===norm(t.cut));if(i<0)throw new Error(`missing ${t.cut}`);lines[i]=`1 ${t.add.name} (${t.add.set}) ${t.add.collector}`;return lines.join('\n');}
interface Sig{keep:number;uptime:number;protection:number;spells:number;draws:number;}function sig(r:Record<string,unknown>):Sig{const b=rec(r.baseline),a=rec(r.advanced);return{keep:num(rec(b.openingHands).functionalKeepRate),uptime:num(rec(a.commanderPressure).battlefieldUptimePercent),protection:num(rec(a.interactionPressure).protectionWinRateWhenChallenged),spells:num(rec(a.cardFlow).averageSpellsCast),draws:num(rec(a.cardFlow).averageCardsDrawnByEffects)};}function delta(a:Sig,b:Sig):Sig{return{keep:b.keep-a.keep,uptime:b.uptime-a.uptime,protection:b.protection-a.protection,spells:b.spells-a.spells,draws:b.draws-a.draws};}function mean(v:Sig[]):Sig{return{keep:avg(v.map(x=>x.keep)),uptime:avg(v.map(x=>x.uptime)),protection:avg(v.map(x=>x.protection)),spells:avg(v.map(x=>x.spells)),draws:avg(v.map(x=>x.draws))};}function sim(d:D,s:{pressure:PodPressureV06;turns:number;seed:number}){return simulateDeckGameplayV06(d.parsed,d.cards,{iterations:1150,advancedIterations:1150,turns:s.turns,seed:s.seed,pressure:s.pressure}) as unknown as Record<string,unknown>;}
function combo(d:D){const n=new Set(d.parsed.main.map(e=>norm(e.name)));return['the destined white mage','walking ballista','diabolic intent','ranger-captain of eos'].every(x=>n.has(x));}
async function main(){const text=await readFile(DECK,'utf8'),base=await resolve(text),policy=await resolvePrintingPolicyV08({printingFamily:'Final Fantasy',includePromos:true,includeSpecialReleases:true});if(base.parsed.totalCards!==100||!validateCommanderDeck(base.parsed,base.cards).isLegal||!base.cards.every(c=>printingMatchesPolicyV08(c,policy,AS_OF)))throw new Error('base truth');const bs=SC.map(s=>sig(sim(base,s))),m0=buildDeckMetrics(base.parsed,base.cards);const results=[];for(const t of TESTS){const d=await resolve(replace(text,t)),m=buildDeckMetrics(d.parsed,d.cards),md=mean(SC.map((s,i)=>delta(bs[i]!,sig(sim(d,s))))),legal=validateCommanderDeck(d.parsed,d.cards).isLegal,ff=d.cards.every(c=>printingMatchesPolicyV08(c,policy,AS_OF));const pass=legal&&ff&&combo(d)&&d.parsed.totalCards===100&&m.landCount===m0.landCount&&m.rampCount>=m0.rampCount-1&&m.protectionCount>=m0.protectionCount-1&&md.keep>=-1.5&&md.uptime>=-4&&md.protection>=-7&&md.spells>=-0.25&&md.draws>=-0.35;results.push({id:t.id,cut:t.cut,add:t.add,manual:t.manual,pass,meanDelta:md,metricsDelta:{mv:m.averageNonlandManaValue-m0.averageNonlandManaValue,ramp:m.rampCount-m0.rampCount,interaction:m.interactionCount-m0.interactionCount,protection:m.protectionCount-m0.protectionCount,early:m.earlyPlayCount-m0.earlyPlayCount}});}results.sort((a,b)=>Number(b.pass)-Number(a.pass)||b.meanDelta.spells-a.meanDelta.spells||b.meanDelta.draws-a.meanDelta.draws);const report={status:'exploratory-high-power-outlier-screen',base:{metrics:m0},results,boundary:'High-power FF-only outlier screen. Simulator may under-model bespoke engines such as Bolas Citadel and opponent-library access; manual card-function review is mandatory.'};await writeFile('scions-spellcraft-a9-high-power-outliers.json',JSON.stringify(report,null,2));const md=['# Scions & Spellcraft A9 — High-Power FF Outliers','',...results.map(r=>`## ${r.id}: ${r.cut} -> ${r.add.name} (${r.add.set}) ${r.add.collector}\n- Screen: **${r.pass?'PASS':'REVIEW'}**\n- Manual thesis: ${r.manual}\n- Δ spells: ${r.meanDelta.spells.toFixed(3)}\n- Δ effect-draws: ${r.meanDelta.draws.toFixed(3)}\n- Δ uptime: ${r.meanDelta.uptime.toFixed(3)}\n- Δ protection: ${r.meanDelta.protection.toFixed(3)}\n- Δ MV / ramp / interaction: ${r.metricsDelta.mv.toFixed(3)} / ${r.metricsDelta.ramp>=0?'+':''}${r.metricsDelta.ramp} / ${r.metricsDelta.interaction>=0?'+':''}${r.metricsDelta.interaction}`),'','Manual review controls acceptance.',''].join('\n');await writeFile('scions-spellcraft-a9-high-power-outliers.md',md);console.log(md);}await main();
